### ISSUE TITLE
Saving a form in Archi 5 beta 4

### ISSUE THREAD

**Issue by galsom** [archi-contribs/form-plugin#33] opened 2023-01-30 19:46 UTC
I'm running currently Archi 5 beta 4 (macOS Silicon) with Form Plugin 1.9.1 on macOS Ventura and noticed that I'm unable to make changes to the design of a form through the save button in the Graphical Editor.

Changing values through the form does work correctly and making modifications to the design as well, only persisting these does not seem to work.

There is no error thrown and the log file with the debug option does show the invocation of the save button.

When comparing the behavior to Archi 4.10, after modifying a form design and saving it, I noticed that the editing form was closed and the changes saved to the design. In Archi 5, the Graphical Editor does not close.

Not sure if it is to early to notify you about this since Archi 5 is still in beta.

**Comment by herve91** [comment] 2023-01-30 20:08
Hi,

Thanks for raising this issue. It's the right timing as it gives me some time to fix it before Archi 5 is officially release. Unfortunately, I do not have a Mac at home at this moment. I need to rush to ask a friend of me to lend me one (again) and do some testing.

I'll let you know asap.

**Comment by galsom** [comment] 2023-01-30 22:53
Not sure if it is OS related. Please as always let me know if I can be of any help.

**Comment by herve91** [comment] 2023-01-30 22:57
Thanks ... will do :)

**Comment by herve91** [comment] 2023-04-07 12:42
Sorry for the very long delai

The issue is related to the upgrade of the Java version and the use of a class that has been deprecated. The fix will be included in the 1.9.2 release that I just sent.

**Closed as completed by herve91** 2023-04-07 12:42 UTC
Labels: bug
