### ISSUE TITLE
Changing Something on the Graphical Editor Results in No Values

### ISSUE THREAD

**Issue by audreykoz** [archi-contribs/form-plugin#22] opened 2019-03-14 19:18 UTC
I'm having this issue on the  4.2.0 version of Archi running on a Mac. Basically, when I change a  value (like adding a new column to display a property or something) and then save, running the form results in no values being displayed. I get this empty table
![Screen Shot 2019-03-14 at 2 17 36 PM](https://user-images.githubusercontent.com/22486586/54385168-f9503280-4663-11e9-9ef1-5287edd8ad4e.png)
:

**Comment by herve91** [comment] 2019-03-15 08:01
Hi Audrey,

As I now the ability to test on a MAC, I'll do some testing this weekend and I'll let you know ASAP.

**Comment by audreykoz** [comment] 2019-04-05 17:48
Thanks! Any updates on this?

**Comment by herve91** [comment] 2019-04-08 12:37
Hi Audrey,

I succeeded to reproduce your issue, but I unfortunately crashed my MAC. I must admit that my work does not let me a lot of time to work on Archi at the moment, but I did not forget you ...

**Comment by audreykoz** [comment] 2019-04-12 15:18
Gotcha, thank you, there's no rush!

**Comment by herve91** [comment] 2019-04-15 19:02
Hi Audrey,

I succeeded to reinstall my MAC, but I cannot remember what I did to reproduce your error. Do you mind providing me with more detailed instructions ?

Thanks and regards
Hervé

**Comment by audreykoz** [comment] 2019-04-19 18:03
Sure! So basically, here's what happens: 
1. I download the plugin, and install it. 
2. I try out the plugin by running it on an Archi folder. This works fine, all my elements and relationships are displayed properly. 
3. I decide to change something about the config file for the form. While I can change something about the form (like changing the title of a tab), this change seems to result in an empty form being displayed when I run it in Archi. 
4. I can delete the plugin and reinstall it, and repeat the whole process, and the same thing happens. It works great until I decide to change some aspect of a config file.

**Comment by herve91** [comment] 2019-04-22 18:37
thanks a lot ... I'll let you know ASAP :)

**Comment by herve91** [comment] 2019-04-30 12:35
Hi Audrey,

I'm on vacation today and I spent some time on your issue. I've found a bug in the graphical editor: the "filter genre" in the generate lines tab. It switches to "AND" even if the form configuration file states "OR" ...
![image](https://user-images.githubusercontent.com/9281982/56961691-a6b7d080-6b54-11e9-9c1d-d06a2bf19763.png)

Could you please confirm you're using such filters in your form ?

Thanks
Hervé

**Comment by herve91** [comment] 2019-04-30 13:34
By the way ... My MAC shows unaligned buttons
![image](https://user-images.githubusercontent.com/9281982/56965337-585aff80-6b5d-11e9-94c8-01b29fd31ede.png)

while there are well rendered on Windows
![image](https://user-images.githubusercontent.com/9281982/56965381-758fce00-6b5d-11e9-829f-029d082c84d2.png)

Do you have the same issue ?

**Comment by herve91** [comment] 2019-04-30 15:38
Version 1.8.11 solves your issue. My apologies for the long delay ...

Best regards
Hervé

**Comment by audreykoz** [comment] 2019-05-03 17:01
Trying it out now, I'll let you know how it goes. Thanks!

**Comment by audreykoz** [comment] 2019-05-03 17:40
Okay, so I've tested it, and it's definitely an improvement. I do find that sometimes I need to go back and toggle those filter buttons (even when they're set to "or" the "and" behavior still shows up), but that seems to fix the issue after I save. Also yes, I do have that unaligned button problem on my Mac.

**Comment by herve91** [comment] 2019-05-03 19:00
Thanks for your feed back.

I close this case as the issue is solved, but I will do some more testing as the "OR" value should not be lost.

Regarding the look and feel on MAC, I need to rework all my plugins GUI as the widgets margin (the space between the border and the text) is not the same on MAC and cannot be changed. So I need to enlarge them ...

Best regards
Hervé

**Closed as completed by herve91** 2019-05-03 19:00 UTC
Labels: bug
